services:
  db:
    image: mongo:4.4.1
    container_name: micro-db
    volumes:
      - ./docker/mongodb-data:/data
    command: --serviceExecutor adaptive
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: microdb
    ports:
      - 27023:27023

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  billing:
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: npm run start:dev billing
    ports:
      - '3002:3002'
    env_file:
      - ./apps/billing/.env
    depends_on:
      - db
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env
    depends_on:
      - db
      - billing
      - auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3003:3003'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
